### ISSUE TITLE
Crashes on start if ~/.todo already exists and is a file

### ISSUE THREAD

**Issue by jpouellet** [mank319/Go-For-It#111]
```
$ rm -rf ~/.todo
$ touch ~/.todo
$ go-for-it     
load_task_stores
Reading file: /home/user/.todo/todo.txt

** (go-for-it:4865): ERROR **: TaskManager.vala:304: Error opening file '/home/user/.todo/todo.txt': Not a directory
zsh: trace trap (core dumped)  go-for-it
```

```
(gdb) bt
#0  0x00007ffff59b315b in g_logv () at /lib64/libglib-2.0.so.0
#1  0x00007ffff59b32cf in g_log () at /lib64/libglib-2.0.so.0
#2  0x0000000000410eaa in task_manager_read_task_file ()
#3  0x0000000000410312 in task_manager_load_tasks ()
#4  0x000000000040fa1a in task_manager_load_task_stores ()
#5  0x000000000040e3d1 in task_manager_construct ()
#6  0x000000000040e437 in task_manager_new ()
#7  0x00000000004222a3 in main_new_window ()
#8  0x0000000000422a08 in _main_command_line ()
#9  0x0000000000422555 in main_real_command_line ()
#10 0x00007ffff0601c58 in ffi_call_unix64 () at /lib64/libffi.so.6
#11 0x00007ffff06016ba in ffi_call () at /lib64/libffi.so.6
#12 0x00007ffff5c810fa in g_cclosure_marshal_generic_va () at /lib64/libgobject-2.0.so.0
#13 0x00007ffff5c80614 in _g_closure_invoke_va () at /lib64/libgobject-2.0.so.0
#14 0x00007ffff5c9a8b3 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#15 0x00007ffff5c9b43f in g_signal_emit () at /lib64/libgobject-2.0.so.0
#16 0x00007ffff5f6d1d3 in g_application_call_command_line () at /lib64/libgio-2.0.so.0
#17 0x00007ffff5f6f224 in g_application_real_local_command_line () at /lib64/libgio-2.0.so.0
#18 0x00007ffff5f6f3f2 in g_application_run () at /lib64/libgio-2.0.so.0
#19 0x0000000000421f97 in main_main ()
#20 0x0000000000421ffa in main ()
```

**Comment by JMoerman** [comment]
88ec741e75c4fbffd2ca2150ec260fb6c2a23f03 should fix this issue.
